# Generated by Django 4.2.5 on 2024-01-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='cleaners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('permanent_address', models.CharField(max_length=2000)),
                ('sex', models.CharField(max_length=6)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('current_address', models.CharField(max_length=2000)),
                ('service', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=6)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
