# Generated by Django 4.2.5 on 2024-01-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_bookings_booking_rename_cleaners_cleaner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(default='invalid service', max_length=20),
            preserve_default=False,
        ),
    ]
