# Generated by Django 4.2.5 on 2024-01-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact_remove_cleaner_phone_number_booking_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='age',
        ),
    ]
