# Generated by Django 4.2.5 on 2024-01-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_subscriber_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
                ('cleaner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cleaner')),
                ('subscriber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subscriber')),
            ],
        ),
    ]
